baseURL = 'https://blog.russellbryant.net'
languageCode = 'en-us'
title = 'Russell Bryant'
theme = 'ananke'
SectionPagesMenu = "main"

[params]
  text_color = ""
  author = "Russell Bryant"
  favicon = ""
  site_logo = ""
  description = ""
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3
  toc = true

[[params.ananke_socials]]
name = "github"
url = "https://github.com/russellb"

